#enviroment of tbox build 

FROM ubuntu:14.04
MAINTAINER Shao kun Yang<shaokunyang@163.com>
RUN apt-get update 
RUN apt-get install -y make
RUN apt-get install -y vim
RUN apt-get install -y build-essential
RUN apt-get install -y openssh-server
RUN apt-get install -y net-tools
RUN apt-get install -y git
RUN mkdir /var/run/sshd  
RUN echo 'root:rootroot' |chpasswd  
RUN sed -ri 's/^PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config  
RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config  
WORKDIR /home/zh/tbox-build
